export type ProtocolParams = {
   a0: number,
   coinsPerUtxoByte: number,
   collateralPercent: number,
   costModel: PlutusVersion<number[]>,
   costModels: PlutusVersion<LanguageViewV1, LanguageViewV2>,
   decentralisationParam: number,
   eMax: number,
   extraEntropy: string,
   keyDeposit: number,
   maxBlockBodySize: number,
   maxBlockExMem: string,
   maxBlockExSteps: string,
   maxBlockHeaderSize: number,
   maxCollateralInputs: number,
   maxTxExMem: string,
   maxTxExSteps: string,
   maxTxSize: number,
   maxValSize: string,
   minFeeA: number,
   minFeeB: number,
   minPoolCost: number,
   minUTxOValue: number,
   nOpt: number,
   poolDeposit: number,
   priceMem: number,
   priceStep: number,
   protocolVersion: {
      major: number,
      minor: number
   },
   rho: number,
   tau: number
}

type PlutusVersion<V1, V2 = V1> = {
   PlutusV1: V1
   PlutusV2: V2
}

export declare type LanguageViewV1 = {
   "bData-cpu-arguments": number,
   "iData-cpu-arguments": number,
   "trace-cpu-arguments": number,
   "mkCons-cpu-arguments": number,
   "fstPair-cpu-arguments": number,
   "mapData-cpu-arguments": number,
   "sndPair-cpu-arguments": number,
   "unBData-cpu-arguments": number,
   "unIData-cpu-arguments": number,
   "bData-memory-arguments": number,
   "cekLamCost-exBudgetCPU": number,
   "cekVarCost-exBudgetCPU": number,
   "headList-cpu-arguments": number,
   "iData-memory-arguments": number,
   "listData-cpu-arguments": number,
   "nullList-cpu-arguments": number,
   "tailList-cpu-arguments": number,
   "trace-memory-arguments": number,
   "mkCons-memory-arguments": number,
   "mkNilData-cpu-arguments": number,
   "unMapData-cpu-arguments": number,
   "cekApplyCost-exBudgetCPU": number,
   "cekConstCost-exBudgetCPU": number,
   "cekDelayCost-exBudgetCPU": number,
   "cekForceCost-exBudgetCPU": number,
   "chooseData-cpu-arguments": number,
   "chooseList-cpu-arguments": number,
   "chooseUnit-cpu-arguments": number,
   "constrData-cpu-arguments": number,
   "fstPair-memory-arguments": number,
   "ifThenElse-cpu-arguments": number,
   "mapData-memory-arguments": number,
   "mkPairData-cpu-arguments": number,
   "sndPair-memory-arguments": number,
   "unBData-memory-arguments": number,
   "unIData-memory-arguments": number,
   "unListData-cpu-arguments": number,
   "cekLamCost-exBudgetMemory": number,
   "cekVarCost-exBudgetMemory": number,
   "headList-memory-arguments": number,
   "listData-memory-arguments": number,
   "nullList-memory-arguments": number,
   "sha2_256-memory-arguments": number,
   "sha3_256-memory-arguments": number,
   "tailList-memory-arguments": number,
   "cekBuiltinCost-exBudgetCPU": number,
   "cekStartupCost-exBudgetCPU": number,
   "mkNilData-memory-arguments": number,
   "unConstrData-cpu-arguments": number,
   "unMapData-memory-arguments": number,
   "cekApplyCost-exBudgetMemory": number,
   "cekConstCost-exBudgetMemory": number,
   "cekDelayCost-exBudgetMemory": number,
   "cekForceCost-exBudgetMemory": number,
   "chooseData-memory-arguments": number,
   "chooseList-memory-arguments": number,
   "chooseUnit-memory-arguments": number,
   "constrData-memory-arguments": number,
   "equalsData-memory-arguments": number,
   "ifThenElse-memory-arguments": number,
   "mkNilPairData-cpu-arguments": number,
   "mkPairData-memory-arguments": number,
   "unListData-memory-arguments": number,
   "blake2b_256-memory-arguments": number,
   "sha2_256-cpu-arguments-slope": number,
   "sha3_256-cpu-arguments-slope": number,
   "cekBuiltinCost-exBudgetMemory": number,
   "cekStartupCost-exBudgetMemory": number,
   "equalsString-memory-arguments": number,
   "indexByteString-cpu-arguments": number,
   "unConstrData-memory-arguments": number,
   "addInteger-cpu-arguments-slope": number,
   "decodeUtf8-cpu-arguments-slope": number,
   "encodeUtf8-cpu-arguments-slope": number,
   "equalsData-cpu-arguments-slope": number,
   "equalsInteger-memory-arguments": number,
   "mkNilPairData-memory-arguments": number,
   "blake2b_256-cpu-arguments-slope": number,
   "appendString-cpu-arguments-slope": number,
   "equalsString-cpu-arguments-slope": number,
   "indexByteString-memory-arguments": number,
   "lengthOfByteString-cpu-arguments": number,
   "lessThanInteger-memory-arguments": number,
   "sha2_256-cpu-arguments-intercept": number,
   "sha3_256-cpu-arguments-intercept": number,
   "addInteger-memory-arguments-slope": number,
   "decodeUtf8-memory-arguments-slope": number,
   "encodeUtf8-memory-arguments-slope": number,
   "equalsByteString-memory-arguments": number,
   "equalsInteger-cpu-arguments-slope": number,
   "modInteger-cpu-arguments-constant": number,
   "modInteger-memory-arguments-slope": number,
   "addInteger-cpu-arguments-intercept": number,
   "consByteString-cpu-arguments-slope": number,
   "decodeUtf8-cpu-arguments-intercept": number,
   "encodeUtf8-cpu-arguments-intercept": number,
   "equalsData-cpu-arguments-intercept": number,
   "appendString-memory-arguments-slope": number,
   "blake2b_256-cpu-arguments-intercept": number,
   "equalsString-cpu-arguments-constant": number,
   "lengthOfByteString-memory-arguments": number,
   "lessThanByteString-memory-arguments": number,
   "lessThanInteger-cpu-arguments-slope": number,
   "modInteger-memory-arguments-minimum": number,
   "multiplyInteger-cpu-arguments-slope": number,
   "sliceByteString-cpu-arguments-slope": number,
   "subtractInteger-cpu-arguments-slope": number,
   "appendByteString-cpu-arguments-slope": number,
   "appendString-cpu-arguments-intercept": number,
   "divideInteger-cpu-arguments-constant": number,
   "divideInteger-memory-arguments-slope": number,
   "equalsByteString-cpu-arguments-slope": number,
   "equalsString-cpu-arguments-intercept": number,
   "addInteger-memory-arguments-intercept": number,
   "consByteString-memory-arguments-slope": number,
   "decodeUtf8-memory-arguments-intercept": number,
   "encodeUtf8-memory-arguments-intercept": number,
   "equalsInteger-cpu-arguments-intercept": number,
   "modInteger-memory-arguments-intercept": number,
   "consByteString-cpu-arguments-intercept": number,
   "divideInteger-memory-arguments-minimum": number,
   "lessThanByteString-cpu-arguments-slope": number,
   "lessThanEqualsInteger-memory-arguments": number,
   "multiplyInteger-memory-arguments-slope": number,
   "quotientInteger-cpu-arguments-constant": number,
   "quotientInteger-memory-arguments-slope": number,
   "sliceByteString-memory-arguments-slope": number,
   "subtractInteger-memory-arguments-slope": number,
   "appendByteString-memory-arguments-slope": number,
   "appendString-memory-arguments-intercept": number,
   "equalsByteString-cpu-arguments-constant": number,
   "lessThanInteger-cpu-arguments-intercept": number,
   "multiplyInteger-cpu-arguments-intercept": number,
   "remainderInteger-cpu-arguments-constant": number,
   "remainderInteger-memory-arguments-slope": number,
   "sliceByteString-cpu-arguments-intercept": number,
   "subtractInteger-cpu-arguments-intercept": number,
   "verifyEd25519Signature-memory-arguments": number,
   "appendByteString-cpu-arguments-intercept": number,
   "divideInteger-memory-arguments-intercept": number,
   "equalsByteString-cpu-arguments-intercept": number,
   "quotientInteger-memory-arguments-minimum": number,
   "consByteString-memory-arguments-intercept": number,
   "lessThanEqualsByteString-memory-arguments": number,
   "lessThanEqualsInteger-cpu-arguments-slope": number,
   "remainderInteger-memory-arguments-minimum": number,
   "lessThanByteString-cpu-arguments-intercept": number,
   "multiplyInteger-memory-arguments-intercept": number,
   "quotientInteger-memory-arguments-intercept": number,
   "sliceByteString-memory-arguments-intercept": number,
   "subtractInteger-memory-arguments-intercept": number,
   "verifyEd25519Signature-cpu-arguments-slope": number,
   "appendByteString-memory-arguments-intercept": number,
   "remainderInteger-memory-arguments-intercept": number,
   "lessThanEqualsByteString-cpu-arguments-slope": number,
   "lessThanEqualsInteger-cpu-arguments-intercept": number,
   "modInteger-cpu-arguments-model-arguments-slope": number,
   "verifyEd25519Signature-cpu-arguments-intercept": number,
   "lessThanEqualsByteString-cpu-arguments-intercept": number,
   "divideInteger-cpu-arguments-model-arguments-slope": number,
   "modInteger-cpu-arguments-model-arguments-intercept": number,
   "quotientInteger-cpu-arguments-model-arguments-slope": number,
   "remainderInteger-cpu-arguments-model-arguments-slope": number,
   "divideInteger-cpu-arguments-model-arguments-intercept": number,
   "quotientInteger-cpu-arguments-model-arguments-intercept": number,
   "remainderInteger-cpu-arguments-model-arguments-intercept": number
}
export declare type LanguageViewV2 = {
   "bData-cpu-arguments": number,
   "iData-cpu-arguments": number,
   "trace-cpu-arguments": number,
   "mkCons-cpu-arguments": number,
   "fstPair-cpu-arguments": number,
   "mapData-cpu-arguments": number,
   "sndPair-cpu-arguments": number,
   "unBData-cpu-arguments": number,
   "unIData-cpu-arguments": number,
   "bData-memory-arguments": number,
   "cekLamCost-exBudgetCPU": number,
   "cekVarCost-exBudgetCPU": number,
   "headList-cpu-arguments": number,
   "iData-memory-arguments": number,
   "listData-cpu-arguments": number,
   "nullList-cpu-arguments": number,
   "tailList-cpu-arguments": number,
   "trace-memory-arguments": number,
   "mkCons-memory-arguments": number,
   "mkNilData-cpu-arguments": number,
   "unMapData-cpu-arguments": number,
   "cekApplyCost-exBudgetCPU": number,
   "cekConstCost-exBudgetCPU": number,
   "cekDelayCost-exBudgetCPU": number,
   "cekForceCost-exBudgetCPU": number,
   "chooseData-cpu-arguments": number,
   "chooseList-cpu-arguments": number,
   "chooseUnit-cpu-arguments": number,
   "constrData-cpu-arguments": number,
   "fstPair-memory-arguments": number,
   "ifThenElse-cpu-arguments": number,
   "mapData-memory-arguments": number,
   "mkPairData-cpu-arguments": number,
   "sndPair-memory-arguments": number,
   "unBData-memory-arguments": number,
   "unIData-memory-arguments": number,
   "unListData-cpu-arguments": number,
   "cekLamCost-exBudgetMemory": number,
   "cekVarCost-exBudgetMemory": number,
   "headList-memory-arguments": number,
   "listData-memory-arguments": number,
   "nullList-memory-arguments": number,
   "sha2_256-memory-arguments": number,
   "sha3_256-memory-arguments": number,
   "tailList-memory-arguments": number,
   "cekBuiltinCost-exBudgetCPU": number,
   "cekStartupCost-exBudgetCPU": number,
   "mkNilData-memory-arguments": number,
   "unConstrData-cpu-arguments": number,
   "unMapData-memory-arguments": number,
   "cekApplyCost-exBudgetMemory": number,
   "cekConstCost-exBudgetMemory": number,
   "cekDelayCost-exBudgetMemory": number,
   "cekForceCost-exBudgetMemory": number,
   "chooseData-memory-arguments": number,
   "chooseList-memory-arguments": number,
   "chooseUnit-memory-arguments": number,
   "constrData-memory-arguments": number,
   "equalsData-memory-arguments": number,
   "ifThenElse-memory-arguments": number,
   "mkNilPairData-cpu-arguments": number,
   "mkPairData-memory-arguments": number,
   "unListData-memory-arguments": number,
   "blake2b_256-memory-arguments": number,
   "sha2_256-cpu-arguments-slope": number,
   "sha3_256-cpu-arguments-slope": number,
   "cekBuiltinCost-exBudgetMemory": number,
   "cekStartupCost-exBudgetMemory": number,
   "equalsString-memory-arguments": number,
   "indexByteString-cpu-arguments": number,
   "unConstrData-memory-arguments": number,
   "addInteger-cpu-arguments-slope": number,
   "decodeUtf8-cpu-arguments-slope": number,
   "encodeUtf8-cpu-arguments-slope": number,
   "equalsData-cpu-arguments-slope": number,
   "equalsInteger-memory-arguments": number,
   "mkNilPairData-memory-arguments": number,
   "blake2b_256-cpu-arguments-slope": number,
   "appendString-cpu-arguments-slope": number,
   "equalsString-cpu-arguments-slope": number,
   "indexByteString-memory-arguments": number,
   "lengthOfByteString-cpu-arguments": number,
   "lessThanInteger-memory-arguments": number,
   "sha2_256-cpu-arguments-intercept": number,
   "sha3_256-cpu-arguments-intercept": number,
   "addInteger-memory-arguments-slope": number,
   "decodeUtf8-memory-arguments-slope": number,
   "encodeUtf8-memory-arguments-slope": number,
   "equalsByteString-memory-arguments": number,
   "equalsInteger-cpu-arguments-slope": number,
   "modInteger-cpu-arguments-constant": number,
   "modInteger-memory-arguments-slope": number,
   "serialiseData-cpu-arguments-slope": number,
   "addInteger-cpu-arguments-intercept": number,
   "consByteString-cpu-arguments-slope": number,
   "decodeUtf8-cpu-arguments-intercept": number,
   "encodeUtf8-cpu-arguments-intercept": number,
   "equalsData-cpu-arguments-intercept": number,
   "appendString-memory-arguments-slope": number,
   "blake2b_256-cpu-arguments-intercept": number,
   "equalsString-cpu-arguments-constant": number,
   "lengthOfByteString-memory-arguments": number,
   "lessThanByteString-memory-arguments": number,
   "lessThanInteger-cpu-arguments-slope": number,
   "modInteger-memory-arguments-minimum": number,
   "multiplyInteger-cpu-arguments-slope": number,
   "sliceByteString-cpu-arguments-slope": number,
   "subtractInteger-cpu-arguments-slope": number,
   "appendByteString-cpu-arguments-slope": number,
   "appendString-cpu-arguments-intercept": number,
   "divideInteger-cpu-arguments-constant": number,
   "divideInteger-memory-arguments-slope": number,
   "equalsByteString-cpu-arguments-slope": number,
   "equalsString-cpu-arguments-intercept": number,
   "serialiseData-memory-arguments-slope": number,
   "addInteger-memory-arguments-intercept": number,
   "consByteString-memory-arguments-slope": number,
   "decodeUtf8-memory-arguments-intercept": number,
   "encodeUtf8-memory-arguments-intercept": number,
   "equalsInteger-cpu-arguments-intercept": number,
   "modInteger-memory-arguments-intercept": number,
   "serialiseData-cpu-arguments-intercept": number,
   "consByteString-cpu-arguments-intercept": number,
   "divideInteger-memory-arguments-minimum": number,
   "lessThanByteString-cpu-arguments-slope": number,
   "lessThanEqualsInteger-memory-arguments": number,
   "multiplyInteger-memory-arguments-slope": number,
   "quotientInteger-cpu-arguments-constant": number,
   "quotientInteger-memory-arguments-slope": number,
   "sliceByteString-memory-arguments-slope": number,
   "subtractInteger-memory-arguments-slope": number,
   "appendByteString-memory-arguments-slope": number,
   "appendString-memory-arguments-intercept": number,
   "equalsByteString-cpu-arguments-constant": number,
   "lessThanInteger-cpu-arguments-intercept": number,
   "multiplyInteger-cpu-arguments-intercept": number,
   "remainderInteger-cpu-arguments-constant": number,
   "remainderInteger-memory-arguments-slope": number,
   "sliceByteString-cpu-arguments-intercept": number,
   "subtractInteger-cpu-arguments-intercept": number,
   "verifyEd25519Signature-memory-arguments": number,
   "appendByteString-cpu-arguments-intercept": number,
   "divideInteger-memory-arguments-intercept": number,
   "equalsByteString-cpu-arguments-intercept": number,
   "quotientInteger-memory-arguments-minimum": number,
   "serialiseData-memory-arguments-intercept": number,
   "consByteString-memory-arguments-intercept": number,
   "lessThanEqualsByteString-memory-arguments": number,
   "lessThanEqualsInteger-cpu-arguments-slope": number,
   "remainderInteger-memory-arguments-minimum": number,
   "lessThanByteString-cpu-arguments-intercept": number,
   "multiplyInteger-memory-arguments-intercept": number,
   "quotientInteger-memory-arguments-intercept": number,
   "sliceByteString-memory-arguments-intercept": number,
   "subtractInteger-memory-arguments-intercept": number,
   "verifyEd25519Signature-cpu-arguments-slope": number,
   "appendByteString-memory-arguments-intercept": number,
   "remainderInteger-memory-arguments-intercept": number,
   "verifyEcdsaSecp256k1Signature-cpu-arguments": number,
   "lessThanEqualsByteString-cpu-arguments-slope": number,
   "lessThanEqualsInteger-cpu-arguments-intercept": number,
   "modInteger-cpu-arguments-model-arguments-slope": number,
   "verifyEcdsaSecp256k1Signature-memory-arguments": number,
   "verifyEd25519Signature-cpu-arguments-intercept": number,
   "lessThanEqualsByteString-cpu-arguments-intercept": number,
   "verifySchnorrSecp256k1Signature-memory-arguments": number,
   "divideInteger-cpu-arguments-model-arguments-slope": number,
   "modInteger-cpu-arguments-model-arguments-intercept": number,
   "quotientInteger-cpu-arguments-model-arguments-slope": number,
   "verifySchnorrSecp256k1Signature-cpu-arguments-slope": number,
   "remainderInteger-cpu-arguments-model-arguments-slope": number,
   "divideInteger-cpu-arguments-model-arguments-intercept": number,
   "quotientInteger-cpu-arguments-model-arguments-intercept": number,
   "verifySchnorrSecp256k1Signature-cpu-arguments-intercept": number,
   "remainderInteger-cpu-arguments-model-arguments-intercept": number
}


// export declare type LanguageView = {
//    PlutusV1: {
//       "bData-cpu-arguments": number,
//       "iData-cpu-arguments": number,
//       "trace-cpu-arguments": number,
//       "mkCons-cpu-arguments": number,
//       "fstPair-cpu-arguments": number,
//       "mapData-cpu-arguments": number,
//       "sndPair-cpu-arguments": number,
//       "unBData-cpu-arguments": number,
//       "unIData-cpu-arguments": number,
//       "bData-memory-arguments": number,
//       "cekLamCost-exBudgetCPU": number,
//       "cekVarCost-exBudgetCPU": number,
//       "headList-cpu-arguments": number,
//       "iData-memory-arguments": number,
//       "listData-cpu-arguments": number,
//       "nullList-cpu-arguments": number,
//       "tailList-cpu-arguments": number,
//       "trace-memory-arguments": number,
//       "mkCons-memory-arguments": number,
//       "mkNilData-cpu-arguments": number,
//       "unMapData-cpu-arguments": number,
//       "cekApplyCost-exBudgetCPU": number,
//       "cekConstCost-exBudgetCPU": number,
//       "cekDelayCost-exBudgetCPU": number,
//       "cekForceCost-exBudgetCPU": number,
//       "chooseData-cpu-arguments": number,
//       "chooseList-cpu-arguments": number,
//       "chooseUnit-cpu-arguments": number,
//       "constrData-cpu-arguments": number,
//       "fstPair-memory-arguments": number,
//       "ifThenElse-cpu-arguments": number,
//       "mapData-memory-arguments": number,
//       "mkPairData-cpu-arguments": number,
//       "sndPair-memory-arguments": number,
//       "unBData-memory-arguments": number,
//       "unIData-memory-arguments": number,
//       "unListData-cpu-arguments": number,
//       "cekLamCost-exBudgetMemory": number,
//       "cekVarCost-exBudgetMemory": number,
//       "headList-memory-arguments": number,
//       "listData-memory-arguments": number,
//       "nullList-memory-arguments": number,
//       "sha2_256-memory-arguments": number,
//       "sha3_256-memory-arguments": number,
//       "tailList-memory-arguments": number,
//       "cekBuiltinCost-exBudgetCPU": number,
//       "cekStartupCost-exBudgetCPU": number,
//       "mkNilData-memory-arguments": number,
//       "unConstrData-cpu-arguments": number,
//       "unMapData-memory-arguments": number,
//       "cekApplyCost-exBudgetMemory": number,
//       "cekConstCost-exBudgetMemory": number,
//       "cekDelayCost-exBudgetMemory": number,
//       "cekForceCost-exBudgetMemory": number,
//       "chooseData-memory-arguments": number,
//       "chooseList-memory-arguments": number,
//       "chooseUnit-memory-arguments": number,
//       "constrData-memory-arguments": number,
//       "equalsData-memory-arguments": number,
//       "ifThenElse-memory-arguments": number,
//       "mkNilPairData-cpu-arguments": number,
//       "mkPairData-memory-arguments": number,
//       "unListData-memory-arguments": number,
//       "blake2b_256-memory-arguments": number,
//       "sha2_256-cpu-arguments-slope": number,
//       "sha3_256-cpu-arguments-slope": number,
//       "cekBuiltinCost-exBudgetMemory": number,
//       "cekStartupCost-exBudgetMemory": number,
//       "equalsString-memory-arguments": number,
//       "indexByteString-cpu-arguments": number,
//       "unConstrData-memory-arguments": number,
//       "addInteger-cpu-arguments-slope": number,
//       "decodeUtf8-cpu-arguments-slope": number,
//       "encodeUtf8-cpu-arguments-slope": number,
//       "equalsData-cpu-arguments-slope": number,
//       "equalsInteger-memory-arguments": number,
//       "mkNilPairData-memory-arguments": number,
//       "blake2b_256-cpu-arguments-slope": number,
//       "appendString-cpu-arguments-slope": number,
//       "equalsString-cpu-arguments-slope": number,
//       "indexByteString-memory-arguments": number,
//       "lengthOfByteString-cpu-arguments": number,
//       "lessThanInteger-memory-arguments": number,
//       "sha2_256-cpu-arguments-intercept": number,
//       "sha3_256-cpu-arguments-intercept": number,
//       "addInteger-memory-arguments-slope": number,
//       "decodeUtf8-memory-arguments-slope": number,
//       "encodeUtf8-memory-arguments-slope": number,
//       "equalsByteString-memory-arguments": number,
//       "equalsInteger-cpu-arguments-slope": number,
//       "modInteger-cpu-arguments-constant": number,
//       "modInteger-memory-arguments-slope": number,
//       "addInteger-cpu-arguments-intercept": number,
//       "consByteString-cpu-arguments-slope": number,
//       "decodeUtf8-cpu-arguments-intercept": number,
//       "encodeUtf8-cpu-arguments-intercept": number,
//       "equalsData-cpu-arguments-intercept": number,
//       "appendString-memory-arguments-slope": number,
//       "blake2b_256-cpu-arguments-intercept": number,
//       "equalsString-cpu-arguments-constant": number,
//       "lengthOfByteString-memory-arguments": number,
//       "lessThanByteString-memory-arguments": number,
//       "lessThanInteger-cpu-arguments-slope": number,
//       "modInteger-memory-arguments-minimum": number,
//       "multiplyInteger-cpu-arguments-slope": number,
//       "sliceByteString-cpu-arguments-slope": number,
//       "subtractInteger-cpu-arguments-slope": number,
//       "appendByteString-cpu-arguments-slope": number,
//       "appendString-cpu-arguments-intercept": number,
//       "divideInteger-cpu-arguments-constant": number,
//       "divideInteger-memory-arguments-slope": number,
//       "equalsByteString-cpu-arguments-slope": number,
//       "equalsString-cpu-arguments-intercept": number,
//       "addInteger-memory-arguments-intercept": number,
//       "consByteString-memory-arguments-slope": number,
//       "decodeUtf8-memory-arguments-intercept": number,
//       "encodeUtf8-memory-arguments-intercept": number,
//       "equalsInteger-cpu-arguments-intercept": number,
//       "modInteger-memory-arguments-intercept": number,
//       "consByteString-cpu-arguments-intercept": number,
//       "divideInteger-memory-arguments-minimum": number,
//       "lessThanByteString-cpu-arguments-slope": number,
//       "lessThanEqualsInteger-memory-arguments": number,
//       "multiplyInteger-memory-arguments-slope": number,
//       "quotientInteger-cpu-arguments-constant": number,
//       "quotientInteger-memory-arguments-slope": number,
//       "sliceByteString-memory-arguments-slope": number,
//       "subtractInteger-memory-arguments-slope": number,
//       "appendByteString-memory-arguments-slope": number,
//       "appendString-memory-arguments-intercept": number,
//       "equalsByteString-cpu-arguments-constant": number,
//       "lessThanInteger-cpu-arguments-intercept": number,
//       "multiplyInteger-cpu-arguments-intercept": number,
//       "remainderInteger-cpu-arguments-constant": number,
//       "remainderInteger-memory-arguments-slope": number,
//       "sliceByteString-cpu-arguments-intercept": number,
//       "subtractInteger-cpu-arguments-intercept": number,
//       "verifyEd25519Signature-memory-arguments": number,
//       "appendByteString-cpu-arguments-intercept": number,
//       "divideInteger-memory-arguments-intercept": number,
//       "equalsByteString-cpu-arguments-intercept": number,
//       "quotientInteger-memory-arguments-minimum": number,
//       "consByteString-memory-arguments-intercept": number,
//       "lessThanEqualsByteString-memory-arguments": number,
//       "lessThanEqualsInteger-cpu-arguments-slope": number,
//       "remainderInteger-memory-arguments-minimum": number,
//       "lessThanByteString-cpu-arguments-intercept": number,
//       "multiplyInteger-memory-arguments-intercept": number,
//       "quotientInteger-memory-arguments-intercept": number,
//       "sliceByteString-memory-arguments-intercept": number,
//       "subtractInteger-memory-arguments-intercept": number,
//       "verifyEd25519Signature-cpu-arguments-slope": number,
//       "appendByteString-memory-arguments-intercept": number,
//       "remainderInteger-memory-arguments-intercept": number,
//       "lessThanEqualsByteString-cpu-arguments-slope": number,
//       "lessThanEqualsInteger-cpu-arguments-intercept": number,
//       "modInteger-cpu-arguments-model-arguments-slope": number,
//       "verifyEd25519Signature-cpu-arguments-intercept": number,
//       "lessThanEqualsByteString-cpu-arguments-intercept": number,
//       "divideInteger-cpu-arguments-model-arguments-slope": number,
//       "modInteger-cpu-arguments-model-arguments-intercept": number,
//       "quotientInteger-cpu-arguments-model-arguments-slope": number,
//       "remainderInteger-cpu-arguments-model-arguments-slope": number,
//       "divideInteger-cpu-arguments-model-arguments-intercept": number,
//       "quotientInteger-cpu-arguments-model-arguments-intercept": number,
//       "remainderInteger-cpu-arguments-model-arguments-intercept": number
//    },
//    PlutusV2: {
//       "bData-cpu-arguments": number,
//       "iData-cpu-arguments": number,
//       "trace-cpu-arguments": number,
//       "mkCons-cpu-arguments": number,
//       "fstPair-cpu-arguments": number,
//       "mapData-cpu-arguments": number,
//       "sndPair-cpu-arguments": number,
//       "unBData-cpu-arguments": number,
//       "unIData-cpu-arguments": number,
//       "bData-memory-arguments": number,
//       "cekLamCost-exBudgetCPU": number,
//       "cekVarCost-exBudgetCPU": number,
//       "headList-cpu-arguments": number,
//       "iData-memory-arguments": number,
//       "listData-cpu-arguments": number,
//       "nullList-cpu-arguments": number,
//       "tailList-cpu-arguments": number,
//       "trace-memory-arguments": number,
//       "mkCons-memory-arguments": number,
//       "mkNilData-cpu-arguments": number,
//       "unMapData-cpu-arguments": number,
//       "cekApplyCost-exBudgetCPU": number,
//       "cekConstCost-exBudgetCPU": number,
//       "cekDelayCost-exBudgetCPU": number,
//       "cekForceCost-exBudgetCPU": number,
//       "chooseData-cpu-arguments": number,
//       "chooseList-cpu-arguments": number,
//       "chooseUnit-cpu-arguments": number,
//       "constrData-cpu-arguments": number,
//       "fstPair-memory-arguments": number,
//       "ifThenElse-cpu-arguments": number,
//       "mapData-memory-arguments": number,
//       "mkPairData-cpu-arguments": number,
//       "sndPair-memory-arguments": number,
//       "unBData-memory-arguments": number,
//       "unIData-memory-arguments": number,
//       "unListData-cpu-arguments": number,
//       "cekLamCost-exBudgetMemory": number,
//       "cekVarCost-exBudgetMemory": number,
//       "headList-memory-arguments": number,
//       "listData-memory-arguments": number,
//       "nullList-memory-arguments": number,
//       "sha2_256-memory-arguments": number,
//       "sha3_256-memory-arguments": number,
//       "tailList-memory-arguments": number,
//       "cekBuiltinCost-exBudgetCPU": number,
//       "cekStartupCost-exBudgetCPU": number,
//       "mkNilData-memory-arguments": number,
//       "unConstrData-cpu-arguments": number,
//       "unMapData-memory-arguments": number,
//       "cekApplyCost-exBudgetMemory": number,
//       "cekConstCost-exBudgetMemory": number,
//       "cekDelayCost-exBudgetMemory": number,
//       "cekForceCost-exBudgetMemory": number,
//       "chooseData-memory-arguments": number,
//       "chooseList-memory-arguments": number,
//       "chooseUnit-memory-arguments": number,
//       "constrData-memory-arguments": number,
//       "equalsData-memory-arguments": number,
//       "ifThenElse-memory-arguments": number,
//       "mkNilPairData-cpu-arguments": number,
//       "mkPairData-memory-arguments": number,
//       "unListData-memory-arguments": number,
//       "blake2b_256-memory-arguments": number,
//       "sha2_256-cpu-arguments-slope": number,
//       "sha3_256-cpu-arguments-slope": number,
//       "cekBuiltinCost-exBudgetMemory": number,
//       "cekStartupCost-exBudgetMemory": number,
//       "equalsString-memory-arguments": number,
//       "indexByteString-cpu-arguments": number,
//       "unConstrData-memory-arguments": number,
//       "addInteger-cpu-arguments-slope": number,
//       "decodeUtf8-cpu-arguments-slope": number,
//       "encodeUtf8-cpu-arguments-slope": number,
//       "equalsData-cpu-arguments-slope": number,
//       "equalsInteger-memory-arguments": number,
//       "mkNilPairData-memory-arguments": number,
//       "blake2b_256-cpu-arguments-slope": number,
//       "appendString-cpu-arguments-slope": number,
//       "equalsString-cpu-arguments-slope": number,
//       "indexByteString-memory-arguments": number,
//       "lengthOfByteString-cpu-arguments": number,
//       "lessThanInteger-memory-arguments": number,
//       "sha2_256-cpu-arguments-intercept": number,
//       "sha3_256-cpu-arguments-intercept": number,
//       "addInteger-memory-arguments-slope": number,
//       "decodeUtf8-memory-arguments-slope": number,
//       "encodeUtf8-memory-arguments-slope": number,
//       "equalsByteString-memory-arguments": number,
//       "equalsInteger-cpu-arguments-slope": number,
//       "modInteger-cpu-arguments-constant": number,
//       "modInteger-memory-arguments-slope": number,
//       "serialiseData-cpu-arguments-slope": number,
//       "addInteger-cpu-arguments-intercept": number,
//       "consByteString-cpu-arguments-slope": number,
//       "decodeUtf8-cpu-arguments-intercept": number,
//       "encodeUtf8-cpu-arguments-intercept": number,
//       "equalsData-cpu-arguments-intercept": number,
//       "appendString-memory-arguments-slope": number,
//       "blake2b_256-cpu-arguments-intercept": number,
//       "equalsString-cpu-arguments-constant": number,
//       "lengthOfByteString-memory-arguments": number,
//       "lessThanByteString-memory-arguments": number,
//       "lessThanInteger-cpu-arguments-slope": number,
//       "modInteger-memory-arguments-minimum": number,
//       "multiplyInteger-cpu-arguments-slope": number,
//       "sliceByteString-cpu-arguments-slope": number,
//       "subtractInteger-cpu-arguments-slope": number,
//       "appendByteString-cpu-arguments-slope": number,
//       "appendString-cpu-arguments-intercept": number,
//       "divideInteger-cpu-arguments-constant": number,
//       "divideInteger-memory-arguments-slope": number,
//       "equalsByteString-cpu-arguments-slope": number,
//       "equalsString-cpu-arguments-intercept": number,
//       "serialiseData-memory-arguments-slope": number,
//       "addInteger-memory-arguments-intercept": number,
//       "consByteString-memory-arguments-slope": number,
//       "decodeUtf8-memory-arguments-intercept": number,
//       "encodeUtf8-memory-arguments-intercept": number,
//       "equalsInteger-cpu-arguments-intercept": number,
//       "modInteger-memory-arguments-intercept": number,
//       "serialiseData-cpu-arguments-intercept": number,
//       "consByteString-cpu-arguments-intercept": number,
//       "divideInteger-memory-arguments-minimum": number,
//       "lessThanByteString-cpu-arguments-slope": number,
//       "lessThanEqualsInteger-memory-arguments": number,
//       "multiplyInteger-memory-arguments-slope": number,
//       "quotientInteger-cpu-arguments-constant": number,
//       "quotientInteger-memory-arguments-slope": number,
//       "sliceByteString-memory-arguments-slope": number,
//       "subtractInteger-memory-arguments-slope": number,
//       "appendByteString-memory-arguments-slope": number,
//       "appendString-memory-arguments-intercept": number,
//       "equalsByteString-cpu-arguments-constant": number,
//       "lessThanInteger-cpu-arguments-intercept": number,
//       "multiplyInteger-cpu-arguments-intercept": number,
//       "remainderInteger-cpu-arguments-constant": number,
//       "remainderInteger-memory-arguments-slope": number,
//       "sliceByteString-cpu-arguments-intercept": number,
//       "subtractInteger-cpu-arguments-intercept": number,
//       "verifyEd25519Signature-memory-arguments": number,
//       "appendByteString-cpu-arguments-intercept": number,
//       "divideInteger-memory-arguments-intercept": number,
//       "equalsByteString-cpu-arguments-intercept": number,
//       "quotientInteger-memory-arguments-minimum": number,
//       "serialiseData-memory-arguments-intercept": number,
//       "consByteString-memory-arguments-intercept": number,
//       "lessThanEqualsByteString-memory-arguments": number,
//       "lessThanEqualsInteger-cpu-arguments-slope": number,
//       "remainderInteger-memory-arguments-minimum": number,
//       "lessThanByteString-cpu-arguments-intercept": number,
//       "multiplyInteger-memory-arguments-intercept": number,
//       "quotientInteger-memory-arguments-intercept": number,
//       "sliceByteString-memory-arguments-intercept": number,
//       "subtractInteger-memory-arguments-intercept": number,
//       "verifyEd25519Signature-cpu-arguments-slope": number,
//       "appendByteString-memory-arguments-intercept": number,
//       "remainderInteger-memory-arguments-intercept": number,
//       "verifyEcdsaSecp256k1Signature-cpu-arguments": number,
//       "lessThanEqualsByteString-cpu-arguments-slope": number,
//       "lessThanEqualsInteger-cpu-arguments-intercept": number,
//       "modInteger-cpu-arguments-model-arguments-slope": number,
//       "verifyEcdsaSecp256k1Signature-memory-arguments": number,
//       "verifyEd25519Signature-cpu-arguments-intercept": number,
//       "lessThanEqualsByteString-cpu-arguments-intercept": number,
//       "verifySchnorrSecp256k1Signature-memory-arguments": number,
//       "divideInteger-cpu-arguments-model-arguments-slope": number,
//       "modInteger-cpu-arguments-model-arguments-intercept": number,
//       "quotientInteger-cpu-arguments-model-arguments-slope": number,
//       "verifySchnorrSecp256k1Signature-cpu-arguments-slope": number,
//       "remainderInteger-cpu-arguments-model-arguments-slope": number,
//       "divideInteger-cpu-arguments-model-arguments-intercept": number,
//       "quotientInteger-cpu-arguments-model-arguments-intercept": number,
//       "verifySchnorrSecp256k1Signature-cpu-arguments-intercept": number,
//       "remainderInteger-cpu-arguments-model-arguments-intercept": number
//    }
// }